name: Deploy with Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            export BRANCH=STAGING
          elif [[ "${{ github.ref }}" == "refs/tags/release-"* ]]; then
            export BRANCH=PROD
          else
            export BRANCH=DEV
          fi
          export AWS_ECR_REGISTRY=${{ env[format('{0}_AWS_ECR_REGISTRY', env.BRANCH)] }}
          export FUNCTION_NAME=${{ env[format('{0}_FUNCTION_NAME', env.BRANCH)] }}
          export BASE_URL=${{ env[format('{0}_BASE_URL', env.BRANCH)] }}
          export FROM=${{ env[format('{0}_FROM', env.BRANCH)] }}
          export NO_OF_POSTS_SENT_TO_USERS=${{ env[format('{0}_NO_OF_POSTS_SENT_TO_USERS', env.BRANCH)] }}
          export OPENAI_API_KEY=${{ env[format('{0}_OPENAI_API_KEY', env.BRANCH)] }}
          export SENDGRID_API_KEY=${{ env[format('{0}_SENDGRID_API_KEY', env.BRANCH)] }}
          export SYNC_HOURS=${{ env[format('{0}_SYNC_HOURS', env.BRANCH)] }}
          export AWS_REGION=eu-west-2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build Docker image
        run: docker build -t ${{ env.FUNCTION_NAME }} .
      - name: Tag Docker image
        run: docker tag ${{ env.FUNCTION_NAME }}:latest ${{ env.AWS_ECR_REGISTRY }}/${{ env.FUNCTION_NAME }}:latest
      - name: Upload Docker image to AWS ECR
        run: docker push ${{ env.AWS_ECR_REGISTRY }}/${{ env.FUNCTION_NAME }}:latest
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.2"
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan -out=tfplan
      - name: Terraform apply
        run: terraform apply tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
