name: Deploy with Terraform
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    environment: 
      FUNCTION_NAME: ${{ env.FUNCTION_NAME_DEV }}
      BASE_URL: ${{ env.BASE_URL_DEV }}
      FROM: ${{ env.FROM_DEV }}
      NO_OF_POSTS_SENT_TO_USERS: ${{ env.NO_OF_POSTS_SENT_TO_USERS_DEV }}
      OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
      SENDGRID_API_KEY: ${{ env. SENDGRID_API_KEY }}
      SYNC_HOURS: ${{ env.SYNC_HOURS }}
      AWS_ECR_REGISTRY: ${{ env.AWS_ECR_REGISTRY }}
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: export AWS_REGION=eu-west-2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build Docker image
        run: docker build -t ${{ env.FUNCTION_NAME_DEV }} .
      - name: Tag Docker image
        run: docker tag ${{ env.FUNCTION_NAME_DEV }}:latest ${{ env.AWS_ECR_REGISTRY }}/${{ env.FUNCTION_NAME_DEV }}:latest
      - name: Upload Docker image to AWS ECR
        run: docker push ${{ env.AWS_ECR_REGISTRY }}/${{ env.FUNCTION_NAME_DEV }}:latest
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.2"
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan -out=tfplan
      - name: Terraform apply
        run: terraform apply tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
